all:
#	gcc A.c -o A
#	gcc B.c -o B
#	gcc C.c -o C
#	gcc D.c -o D
#	gcc E.c -o E
#	gcc F.c -o F
#	gcc G.c -o G
	gcc H.c -o H
#	gcc I.c -o I
#	gcc J.c -o J
#	gcc K.c -o K
#	gcc L.c -o L
#	gcc M.c -o M
#	gcc N.c -o N

clean: